#!/bin/bash
if ! [[ $(head -n 1 $1) =~ ^#[0-9]+:[[:space:]][A-Z].*|^Merge.* ]]; then
    echo "Your commit message does not conform to the required pattern."
    echo "Expected pattern: '#<issue-number>: <Imperative message>'"
    echo "Example: '#123: Add profile view'"
    exec < /dev/tty
    read -p "Are you sure you want to continue with this commit message? (y/N) " -n 1 -r
    echo
    if ! [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Commit aborted."
        exit 1
    fi
fi
