#!/bin/bash
changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
    echo "$changed_files" | grep -E --quiet "$1" && eval "$2"
}

# `npm install` and `npm prune` if the `package.json` file gets changed
# to update all the nodejs dependencies deleting the unused packages (not listed into the `package.json` file)
check_run package.json "npm install && npm prune"
